Repository g12-4soat/techlanches-pagamento, pull requests merged in 2024-07, with the labels that each got.

#17 Feature/saga coreografada
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.DynamoDB/Repositories/PagamentoRepository.cs
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.RabbitMq/IBaseMessage.cs
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.RabbitMq/Messaging/IRabbitMqService.cs
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.RabbitMq/Messaging/RabbitMqService.cs
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.RabbitMq/Options/RabbitOptions.cs
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.RabbitMq/PedidoCriadoMessage.cs
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.RabbitMq/PedidoMessage.cs
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.RabbitMq/PedidoStatusMessage.cs
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.RabbitMq/TechLanches.Pagamento.Adapter.RabbitMq.csproj
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.API/Configuration/DependecyInjectionConfig.cs
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.API/Endpoints/PagamentoEndpoints.cs
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.API/Program.cs
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.API/TechLanches.Pagamento.Adapter.API.csproj
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.API/appsettings.Development.json
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.API/appsettings.Production.json
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.API/appsettings.json
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.Consumer/PagamentoConsumerHostedService.cs
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.Consumer/TechLanches.Pagamento.Adapter.Consumer.csproj
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/Controllers/IPagamentoController.cs
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/Controllers/PagamentoController.cs
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/Ports/Repositories/IPagamentoRepository.cs
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/TechLanches.Pagamento.Application.csproj
  src/TechLanches.Pagamento/TechLanches.Pagamento.sln
  test/TechLanches.Pagamento.UnitTests/BDDTests/Services/PagamentoTest.cs
  test/TechLanches.Pagamento.UnitTests/UnitTests/Adapter/Repositories/PagamentoRepositoryTests.cs
  test/TechLanches.Pagamento.UnitTests/UnitTests/Application/Controllers/PagamentoControllerTest.cs
Labels: enhancement

#19 Feature/outbox
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.DynamoDB/Models/OutboxMessageDbModel.cs
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.DynamoDB/Repositories/OutboxRepository.cs
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.DynamoDB/Repositories/PagamentoRepository.cs
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.API/Configuration/DependecyInjectionConfig.cs
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.API/Program.cs
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.API/TechLanches.Pagamento.Adapter.API.csproj
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.Outbox/OutboxConsumerHostedService.cs
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.Outbox/Services/IOutboxService.cs
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.Outbox/Services/OutboxService.cs
  src/TechLanches.Pagamento/Adapter/Driver/TechLanches.Pagamento.Adapter.Outbox/TechLanches.Pagamento.Adapter.Outbox.csproj
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/Controllers/PagamentoController.cs
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/Gateways/Interfaces/IPagamentoGateway.cs
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/Gateways/PagamentoGateway.cs
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/Ports/Repositories/IOutboxRepository.cs
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Domain/Aggregates/Outbox.cs
  src/TechLanches.Pagamento/TechLanches.Pagamento.sln
Labels: enhancement

#21 Update README.md
  README.md
Labels: documentation

#24 correção endpoint
  src/TechLanches.Pagamento/Adapter/Driven/TechLanches.Pagamento.Adapter.DynamoDB/Repositories/PagamentoRepository.cs
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/Controllers/PagamentoController.cs
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/Gateways/PedidoGateway.cs
  src/TechLanches.Pagamento/Core/TechLanches.Pagamento.Application/TechLanches.Pagamento.Application.csproj
  test/TechLanches.Pagamento.UnitTests/UnitTests/Adapter/Repositories/PagamentoRepositoryTests.cs
Labels: bug
